export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED';
export const HOME_PAGE = 'HOME_PAGE';
export const ABOUT_PAGE = 'ABOUT_PAGE';
